# Generated by Django 5.1.2 on 2025-05-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_slug_361555_idx',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
