# Generated by Django 5.1.2 on 2025-05-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_blog_blogpo_slug_361555_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='avatar',
        ),
    ]
