# Generated by Django 5.1.2 on 2025-05-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
