# Generated by Django 5.1.2 on 2025-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='main.course'),
        ),
    ]
