# Generated by Django 5.1.2 on 2025-05-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_programminglanguage_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.programminglanguage'),
        ),
    ]
