# Generated by Django 5.1.2 on 2025-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_journalist',
            field=models.BooleanField(default=False),
        ),
    ]
