# Generated by Django 5.1.2 on 2025-06-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_author_is_journalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_journalist_only',
            field=models.BooleanField(default=False),
        ),
    ]
