# Generated by Django 5.1.2 on 2025-06-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_keepintouch_remove_author_is_journalist_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_status',
            field=models.CharField(choices=[('none', 'Did not submit'), ('pending', 'In processing'), ('approved', 'Confirmed'), ('rejected', 'Refused')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='author',
            name='journalist_reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='journalist_status',
            field=models.CharField(choices=[('none', 'Did not submit'), ('pending', 'In processing'), ('approved', 'Confirmed'), ('rejected', 'Refused')], default='none', max_length=16),
        ),
    ]
