# Generated by Django 5.1.2 on 2025-06-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_author_author_reject_reason_author_author_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('author', 'Author'), ('journalist', 'Journalist'), ('author_journalist', 'Author & Journalist')], default='student', max_length=40),
        ),
    ]
