# Generated by Django 5.1.2 on 2025-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_certificate_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hash_code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
