# Generated by Django 5.1.2 on 2025-06-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_courseprogress_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
