# Generated by Django 5.1.2 on 2025-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_moderator_created_at_moderator_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_scheduled_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
