# Generated by Django 5.1.2 on 2025-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_student_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('author', 'Author'), ('journalist', 'Journalist'), ('author_journalist', 'Author & Journalist'), ('moderator', 'Moderator')], default='student', max_length=40),
        ),
    ]
