# Generated by Django 5.1.2 on 2025-06-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_finalexam_finalexamquestion_finalexamoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalexamattempt',
            name='cooldown_until',
        ),
    ]
