# Generated by Django 5.1.2 on 2025-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_finalexamattempt_cooldown_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
