# Generated by Django 5.1.2 on 2025-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_certificate_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
