# Generated by Django 5.1.2 on 2024-12-04 00:39

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('about', models.TextField(default='No information available.')),
                ('subscribed_courses', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('subscribed_courses', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text="Enter duration (e.g., '3 weeks' or '1 day')", max_length=20, validators=[myapp.models.validate_course_duration])),
                ('level', models.CharField(choices=[('all', 'All Levels'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='all', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myapp.author')),
                ('students', models.ManyToManyField(blank=True, related_name='courses_subscribed_to', to='myapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='course_list',
            field=models.ManyToManyField(blank=True, related_name='authored_courses', to='myapp.course'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20, validators=[myapp.models.validate_module_duration])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('uploaded_video', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='myapp.course')),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='myapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default='', max_length=512)),
                ('refresh_token', models.CharField(default='', max_length=512)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
