# Generated by Django 5.1.2 on 2024-10-25 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_author_username_activesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='device_info',
        ),
        migrations.AddField(
            model_name='activesession',
            name='access_token',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='activesession',
            name='refresh_token',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
