# Generated by Django 5.1.2 on 2024-12-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_email_alter_student_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
