# Generated by Django 5.1.2 on 2024-10-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_activesession_device_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='module',
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default='No text available'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='course_images/'),
        ),
    ]
