# Generated by Django 5.1.2 on 2024-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_comment_text_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribed_courses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
