# Generated by Django 5.1.2 on 2024-10-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_title_module_module_course_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
    ]
