# Generated by Django 5.1.2 on 2025-02-21 22:01

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[myapp.models.validate_phone_number]),
        ),
    ]
