# Generated by Django 5.1.2 on 2024-10-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_course_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subscribed_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='subscribed_courses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
