# Generated by Django 5.1.2 on 2025-02-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_id']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_id',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='module_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'module_id')},
        ),
    ]
