# Generated by Django 5.1.2 on 2024-12-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_course_lessons_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_subscribed_to', to='myapp.student'),
        ),
    ]
