# Generated by Django 5.1.2 on 2025-02-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_module_options_lesson_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_id',
            new_name='number',
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'number')},
        ),
    ]
