# Generated by Django 5.1.2 on 2025-01-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_post_author_rename_module_module_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
