# Generated by Django 5.1.2 on 2025-02-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_module_options_rename_module_id_module_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
