# Generated by Django 5.1.2 on 2025-02-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_lesson_number_alter_module_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='number',
            new_name='module_id',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'lesson_id')},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'module_id')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
    ]
