# Generated by Django 5.1.2 on 2025-01-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_student_about_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_courses', to='myapp.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='published_courses',
            field=models.ManyToManyField(blank=True, related_name='published_by_authors', to='myapp.course'),
        ),
    ]
