# Generated by Django 5.1.2 on 2025-05-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_remove_student_favorite_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quiz', 'Question & Answer'), ('code', 'Code Exercise')], max_length=10)),
                ('title', models.CharField(max_length=255, verbose_name='Title or Question')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (optional)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('submitted_output', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by_teacher', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exerciseoption')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_input', models.TextField(blank=True, null=True, verbose_name='Sample Input (optional)')),
                ('expected_output', models.TextField(verbose_name='Expected Output (Required)')),
                ('initial_code', models.TextField(blank=True, null=True, verbose_name='Starter Code (optional)')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='exercises.exercise')),
            ],
        ),
    ]
