# Generated by Django 5.1.2 on 2025-05-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_programminglanguage_exercise_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='language',
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
    ]
