# Generated by Django 5.1.2 on 2025-05-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_language_delete_programminglanguage'),
        ('main', '0008_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='main.programminglanguage'),
        ),
    ]
