# Generated by Django 5.1.2 on 2025-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('mcq', 'Question & Answer'), ('code', 'Code Exercise')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exercisesolution',
            name='expected_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercisesolution',
            name='initial_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesolution',
            name='sample_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
